### ISSUE TITLE
checking the PM2 logs gives me this

### ISSUE THREAD

**Issue by jaapbakker88** [murphyj/mailgunner#2]
I'm on Ubuntu 14.04
NPM 2.15
Node 4.4.7

```
mailgunner-0 (err):     at Function.Module._load (module.js:276:25)
mailgunner-0 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
mailgunner-0 (err):     at Module.require (module.js:353:17)
mailgunner-0 (err):     at require (internal/module.js:12:17)
mailgunner-0 (err):     at Object.<anonymous> (/var/www/mailgunner/app.js:3:12)
mailgunner-0 (err):     at Module._compile (module.js:409:26)
mailgunner-0 (err):     at Object.Module._extensions..js (module.js:416:10)
mailgunner-0 (err):     at Module.load (module.js:343:32)
mailgunner-0 (err):     at Function.Module._load (module.js:300:12)
mailgunner-0 (err): Error: Cannot find module 'cors'
mailgunner-0 (err):     at Function.Module._resolveFilename (module.js:325:15)
mailgunner-0 (err):     at Function.Module._load (module.js:276:25)
mailgunner-0 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
mailgunner-0 (err):     at Module.require (module.js:353:17)
mailgunner-0 (err):     at require (internal/module.js:12:17)
mailgunner-0 (err):     at Object.<anonymous> (/var/www/mailgunner/app.js:3:12)
mailgunner-0 (err):     at Module._compile (module.js:409:26)
mailgunner-0 (err):     at Object.Module._extensions..js (module.js:416:10)
mailgunner-0 (err):     at Module.load (module.js:343:32)
mailgunner-0 (err):     at Function.Module._load (module.js:300:12)
```

**Comment by jaapbakker88** [comment]
Alright, I fixed this by adding the CORS module to the app, now it seems to be running. But the mailgun.myurl.com/api/submit/:mail Does just return me an error page of my main website. Do you have any idea how to fix this? Sorry for bothering. I'm still pretty new to all this stuff

**Comment by murphyj** [comment]
@jaapbakker88 have you configured your config file with the correct mailgun parameters?

You can try using your sandbox credentials locally.

**Comment by murphyj** [comment]
Hi Jaappakker,

Have you added the correct credentials for Mailgunner for accessing the API?

Regards

_James Murphy_   Founder, Devangst Enterprises Ltd
[image: photo] Mobile: +44 7480 831 253
Email: developerangst@gmail.com
Skype: developerangst@gmail.com <#>
Website: http://devangst.com
Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=773482359579331

**Comment by murphyj** [comment]
@jaapbakker88 just remembered. When you're hosting mailgunner you also need to make sure you can send and receive mail to the Mailgun API. Make sure you've added the CNAME etc. records.

See: https://documentation.mailgun.com/quickstart-sending.html

**Comment by jaapbakker88** [comment]
I'll try setting up everything from scratch again. Does the mailgun domain have to be the same one as the one I'm hosting the script? Eg. Mailgun domain: mg.example.com and domain where I'm hosting and sending from: somethingelse.nl

Jaap Bakker

On za 27 aug. 2016 at 21:52 James Murphy

<
mailto:James Murphy notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/jaapbakker88
just remembered. When you're hosting mailgunner you also need to make sure you can send and receive mail to the Mailgun API. Make sure you've added the CNAME etc. records.

See:
https://documentation.mailgun.com/quickstart-sending.html

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/murphyj/mailgunner/issues/2#issuecomment-242937361
, or

**Comment by murphyj** [comment]
Realised I didn't answer the last question.

No the domain can be different. There's no cross-domain restrictions as far as I know. Not from the local server anyway.
