### ISSUE TITLE
front end ?

### ISSUE THREAD

**Issue by suriyaJaay** [murphyj/mailgunner#3]
hi
can you pls provide front end part ?

thank you

**Comment by murphyj** [comment]
Hi Suriya

Apologies this is years afterwards. I really didn't give this the time and attention it deserved.

In answer to your question. There's no frontend. This is entirely a backend api that you can run on it's own. It's a microservice purely to send emails to the Mailgun API. A wrapper so to speak.

Hope that clears things up.
